name: Test React App
on: push
jobs:
  test_my_app_react:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test React App
        run: npm run test